### ISSUE TITLE
Adding some options multiple times to the command-line ends up with a list of values in config

### ISSUE THREAD

**Issue by jkovacs-hwx** [cloudera-labs/hms-mirror#166]
E.g. using 
```
hms-mirror  \
--external-warehouse-directory /warehouse/tablespace/external/hive \
... \
--external-warehouse-directory /warehouse/tablespace/external/hive \
...
```
ends up with a config value:
```
externalDirectory: "/warehouse/tablespace/external/hive,/warehouse/tablespace/external/hive"
```
...which could cause issues at runtime.

Command should either fail or should use only the last defined value for configs that should have single values.

**Comment by dstreev** [comment]
This looks like a bug in the commons-cli library where the values are combined even though the option has been configured to accept only 1 argument.

**Comment by jkovacs-hwx** [comment]
I wasn't sure how these are picked up but tested and found that unfortunately used as a single value:
Using:
```
  --external-warehouse-directory /data/hive/external --warehouse-directory /data/hive/managed \
  --external-warehouse-directory /data/hive/external --warehouse-directory /data/hive/managed
```

Got in session-config.yaml:
```
  warehouse:
    source: "GLOBAL"
    externalDirectory: "/data/hive/external,/data/hive/external"
    managedDirectory: "/data/hive/managed,/data/hive/managed"
```

and in RIGHT_execute.sql:
```
-- Alter Database Location
ALTER DATABASE mydb SET LOCATION "hdfs://cdpprod/data/hive/external,/data/hive/external/hive";
-- Alter Database Managed Location
ALTER DATABASE mydb SET MANAGEDLOCATION "hdfs://cdpprod/data/hive/managed,/data/hive/managed/mydb";
```
