### ISSUE TITLE
HDP 3 Hive doesn't support MANAGEDLOCATION attribute for Databases.

### ISSUE THREAD

**Issue by dstreev** [cloudera-labs/hms-mirror#52]
HDP 3 was incomplete in its EXTERNAL/MANAGED table location management.

Add `hdpHive3: true` to the clusters configuration in the configuration yaml file.

```
clusters:
  LEFT:
    environment: "LEFT"
    legacyHive: false
    hdpHive3: true
```
