### ISSUE TITLE
Add option to enabled / disable stats collection on sql transfers

### ISSUE THREAD

**Issue by dstreev** [cloudera-labs/hms-mirror#59]
hive.stats.autogather and hive.stats.column.autogather should have options to set when doing SQL inserts.

If disabled, which should be the default, we should build a script to run the stats collection on the tables in another file.

**Comment by dstreev** [comment]
This is set in the configuration file for the cluster (LEFT and RIGHT).  For the LEFT, set this to deal with transfer data movement.  The settings are 'false' by default, which will turn off stats for the inserts.

```yaml
clusters:
  LEFT|RIGHT:
    enableAutoTableStats: false|true
    enableAutoColumnStats: false|true
```
